-- 01_create_banco_bisa.sql
-- Crear usuario si no existe
DECLARE
    user_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO user_count FROM dba_users WHERE username = 'BANCO_BISA';
    IF user_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER BANCO_BISA IDENTIFIED BY root123';
        EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO BANCO_BISA';
        EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO BANCO_BISA';
    END IF;
END;
/

-- Conectar como el usuario
CONNECT BANCO_BISA/root123@XEPDB1;

-- Crear tabla (Oracle no tiene IF NOT EXISTS)
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE Cuentas (
        Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        NroIdentificacion VARCHAR2(20) NOT NULL,
        Nombres VARCHAR2(100) NOT NULL,
        Apellidos VARCHAR2(100) NOT NULL,
        NroCuenta VARCHAR2(30) NOT NULL UNIQUE,
        IdBanco NUMBER(2) DEFAULT 5 NOT NULL,
        SaldoUSD NUMBER(18,4) NOT NULL,
        SaldoBs NUMBER(18,4) NULL,
        TipoCambioAplicado NUMBER(10,4) NULL,
        FechaConversion TIMESTAMP NULL,
        CodigoVerificacion CHAR(8) NULL,
        LoteId VARCHAR2(50) NULL,
        DatosCifrados CLOB,
        AlgoritmoUsado VARCHAR2(50) DEFAULT ''Cifrado Hill'',
        FechaRegistro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FechaActualizacion TIMESTAMP NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Crear índices (Oracle no tiene IF NOT EXISTS)
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_nrocuenta ON Cuentas(NroCuenta)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_idbanco ON Cuentas(IdBanco)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
